name: Discord Sync

on:
  schedule:
    - cron: '0 0 * * *' # Будет запускаться автоматически каждый день в полночь
  push:
    paths:
      - 'rules.json'    # Будет запускаться САМ, как только обновится файл с правилами
      - 'db.json'
  workflow_dispatch:    # Оставляет возможность запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install discord.js

      - name: Run Sync
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
        run: node sync_discord.js
